# Generated by Django 5.0.4 on 2026-10-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customprofilemodel_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customprofilemodel",
            name="iban",
            field=models.CharField(
                blank=True, max_length=26, null=True, verbose_name="شماره شبا"
            ),
        ),
    ]
