# Generated by Django 4.2.6 on 2024-03-22 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customprofilemodel_is_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customprofilemodel',
            name='user_code',
        ),
    ]
