# Generated by Django 4.2.6 on 2024-03-23 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customprofilemodel_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customprofilemodel',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='پروفایل تکمیل شده؟'),
        ),
    ]
