# Generated by Django 4.2.6 on 2024-03-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customprofilemodel_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customprofilemodel',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='موبایل'),
        ),
    ]
