# Generated by Django 5.0.4 on 2024-06-01 00:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_contact_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 6, 1, 0, 28, 2, 152199, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
