version: '3.8'

services:
  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: shop_db
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    volumes:
      - ./data/pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "4050:80"

  web:
    image: django_shop_3
    container_name: django_shop_3
    build:
      dockerfile: Dockerfile
      context: ./shop
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./shop:/app
    ports:
      - "8001:8000"
    environment:
      - SECRET_KEY=django-insecure-of640&szwnh)s-u$1o33&81v42g&m7#3=z-3w-=cfj6*4er#-(
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - PG_DB=shop_db
      - PG_USER=root
      - PG_PASSWORD=root
      - PG_HOST=db
      - PG_PORT=5432
    depends_on:
      - db

  celery:
    container_name: celery_proj
    build:
      context: ./shop
      dockerfile: Dockerfile
    command: celery -A shopproject.celery worker -l INFO
    volumes:
      - ./shop:/app
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=rpc://
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - DEBUG=True
      - SECRET_KEY=django-insecure-beuu&e-)-p3cluy@f8ebcg^ye8s9f5#-83g6t7^g8_mltzdb+0
      - C_FORCE_ROOT=True
    depends_on:
      - web
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: project_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  celery_beat:
    container_name: django_celery_beat
    build:
      dockerfile: Dockerfile
      context: ./shop
    command: celery -A shopproject.celery beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./shop:/app
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=rpc://
      - SECRET_KEY=django-insecure-of640&szwnh)s-u$1o33&81v42g&m7#3=z-3w-=cfj6*4er#-(
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - PG_DB=shop_db
      - PG_USER=root
      - PG_PASSWORD=root
      - PG_HOST=db
      - PG_PORT=5432
    depends_on:
      - web
      - rabbitmq

  flower:
    image: mher/flower
    ports:
      - "4445:5555"
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//

volumes:
  db:
  pgadmin:
