# Generated by Django 4.2.6 on 2023-10-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='addres',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='profile',
            name='back_money',
            field=models.CharField(blank=True, default='شماره شبا', max_length=50, null=True, verbose_name='Back money'),
        ),
        migrations.AddField(
            model_name='profile',
            name='customer_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/%Y/%m/%d', verbose_name='User Image'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.BooleanField(default=False, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='shomare_cart',
            field=models.IntegerField(blank=True, null=True, verbose_name='shomare_cart'),
        ),
        migrations.AddField(
            model_name='profile',
            name='shomare_shaba',
            field=models.IntegerField(blank=True, null=True, verbose_name='shomare_shaba'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='profile',
            name='zipcode',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='State'),
        ),
    ]
