# Generated by Django 4.2.6 on 2023-10-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_email_remove_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.BooleanField(choices=[(False, 'مرد'), (True, 'زن')], default=False, verbose_name='جنسیت'),
        ),
    ]
