# Generated by Django 4.2.6 on 2024-03-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customprofilemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customprofilemodel',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
