# Generated by Django 4.2.6 on 2023-10-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_national_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='shomare_cart',
        ),
        migrations.AddField(
            model_name='profile',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='شماره کارت'),
        ),
        migrations.AddField(
            model_name='profile',
            name='iban',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='شماره شبا'),
        ),
    ]
