# Generated by Django 4.2.6 on 2023-10-27 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_profile_shomare_cart_profile_card_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='shomare_shaba',
        ),
    ]
