# Generated by Django 4.2.6 on 2024-03-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_customprofilemodel_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customprofilemodel',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='پروفایل تکمیل شده؟>'),
        ),
    ]
