# Generated by Django 4.2.6 on 2023-11-19 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0010_alter_profile_address_alter_profile_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='موضوع')),
                ('description', models.TextField(verbose_name='پیام به کاربر')),
                ('message_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال پیام')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پیام به کاربر',
                'verbose_name_plural': 'پیام به کاربر ها',
            },
        ),
    ]
