# Generated by Django 4.2.6 on 2023-10-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
    ]
