# Generated by Django 4.2.6 on 2023-10-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogs_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_blog',
            name='slug',
            field=models.SlugField(default=1, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
