# Generated by Django 4.2.6 on 2023-11-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blogs_create_date_alter_blogs_update_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت وبلاگ'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش وبلاگ'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت'),
        ),
    ]
