# Generated by Django 4.2.6 on 2023-10-24 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='last name'),
        ),
    ]
