# Generated by Django 4.2.6 on 2023-10-25 00:05

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_comment_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=django_jalali.db.models.jDateTimeField(verbose_name='تاریخ تحویل'),
        ),
    ]
