# Generated by Django 4.2.6 on 2023-10-25 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_contact_product_product_contact_product_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_product',
            name='message_product',
        ),
        migrations.RemoveField(
            model_name='contact_product',
            name='username',
        ),
    ]
