# Generated by Django 4.2.6 on 2023-10-25 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_contact_product_message_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_product',
            name='message_product',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact_product',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.customer'),
            preserve_default=False,
        ),
    ]
