# Generated by Django 4.2.6 on 2023-10-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_contact_product_message_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(default=1, verbose_name='Category slug'),
            preserve_default=False,
        ),
    ]
