# Generated by Django 4.2.6 on 2023-11-02 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_orderitem_discounted_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'سفارش'},
        ),
    ]
