# Generated by Django 4.2.6 on 2023-11-02 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارش ها'},
        ),
    ]
