# Generated by Django 4.2.6 on 2023-11-02 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنت ها'},
        ),
        migrations.AlterModelOptions(
            name='contact_product',
            options={'verbose_name': 'نظرات در محصولات', 'verbose_name_plural': 'نظرات در مورد محصولات'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'صورت حساب', 'verbose_name_plural': 'صورت حساب ها'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'جزئیات سفارش', 'verbose_name_plural': 'جزئیات سفارش ها'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'وضعیت سفارش', 'verbose_name_plural': 'وضعیت سفارش ها'},
        ),
    ]
