# Generated by Django 4.2.6 on 2023-11-02 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_comment_options_alter_contact_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'برند', 'verbose_name_plural': 'برند ها'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'اطلاعیه', 'verbose_name_plural': 'اطلاعیه ها'},
        ),
        migrations.AlterModelOptions(
            name='offers',
            options={'verbose_name': 'تخفیف', 'verbose_name_plural': 'تخفیفات'},
        ),
    ]
