# Generated by Django 4.2.6 on 2023-11-03 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_code',
            field=models.IntegerField(verbose_name='کد برند'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(max_length=50, verbose_name='نام برند'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/brand/%Y/%m/%d', verbose_name='عکس برند'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='category_barnd',
            field=models.ManyToManyField(to='shop.category', verbose_name='دسته بندی برند ها'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_code',
            field=models.IntegerField(verbose_name='کد دسته بندی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50, verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/category/%Y/%m/%d', verbose_name='عکس دسته بندی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(unique=True, verbose_name='یو ار ال دسته بندی'),
        ),
        migrations.AlterField(
            model_name='info',
            name='product_info',
            field=models.TextField(verbose_name='اطلاعیه محصول'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='offer_name',
            field=models.CharField(max_length=50, verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='offer_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/offer/%Y/%m/%d', verbose_name='عکس تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='bluetooth',
            field=models.CharField(choices=[('دارد', 'دارد'), ('ندارد', 'ندارد')], default=False, max_length=20, verbose_name='بلوتوث'),
        ),
        migrations.AlterField(
            model_name='product',
            name='capability',
            field=models.CharField(max_length=20, verbose_name='قابلیت محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mini_description',
            field=models.CharField(max_length=50, verbose_name='توضیح کوتاه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.IntegerField(blank=True, null=True, verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/product/%Y/%m/%d', verbose_name='عکس اصلی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic2',
            field=models.ImageField(blank=True, null=True, upload_to='images/product/productimage/%Y/%m/%d', verbose_name='عکس 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic3',
            field=models.ImageField(blank=True, null=True, upload_to='images/product/productimage/%Y/%m/%d', verbose_name='عکس 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic4',
            field=models.ImageField(blank=True, null=True, upload_to='images/product/productimage/%Y/%m/%d', verbose_name='عکس 4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic5',
            field=models.ImageField(blank=True, null=True, upload_to='images/product/productimage/%Y/%m/%d', verbose_name='عکس 5'),
        ),
        migrations.AlterField(
            model_name='product',
            name='platform_os',
            field=models.CharField(max_length=50, verbose_name='سیستم عامل'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='قیمت محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.brand', verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.IntegerField(verbose_name='کد محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_color',
            field=models.CharField(max_length=20, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(verbose_name='توضیحات تکمیلی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_inf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.info', verbose_name='اطلاعیه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=20, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_number',
            field=models.PositiveIntegerField(verbose_name='تعداد موجود محصول در انبار'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.offers', verbose_name='دسته بندی تخفیفات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_rate',
            field=models.IntegerField(verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='product',
            name='resolution',
            field=models.IntegerField(verbose_name='رزولوشون عکس'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(verbose_name='یو ار ال محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.TextField(verbose_name='مشخصات فنی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='technology',
            field=models.CharField(max_length=50, verbose_name='تکنولوژی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='time_send',
            field=models.PositiveIntegerField(verbose_name='زمان ارسال'),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش'),
        ),
    ]
