# Generated by Django 4.2.6 on 2023-11-03 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0024_alter_brand_brand_code_alter_brand_brand_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(verbose_name='کامنت'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(verbose_name='تاریخ ساخت کامنت'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.PositiveIntegerField(default=False, verbose_name='امتیاز به محصول'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری'),
        ),
        migrations.AlterField(
            model_name='contact_product',
            name='message_product',
            field=models.TextField(verbose_name='نظر در مورد محصول'),
        ),
        migrations.AlterField(
            model_name='contact_product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='contact_product',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ فاکتور'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.order', verbose_name='اطلاعیه'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری مشتری'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان سفارش'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری مشتری'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='تخفیف محصول'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_cost',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='هزینه محصول'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_count',
            field=models.PositiveIntegerField(verbose_name='تعداد محصول'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_price',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='قیمت محصول'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.invoice', verbose_name='فاکتور'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'انتظار'), ('failed', 'ناموفق'), ('completed', 'تکمیل شده')], default='pending', max_length=50, verbose_name='وضغیت'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تراکنش'),
        ),
    ]
