# Generated by Django 4.2.6 on 2023-11-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_comment_comment_alter_comment_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=50, verbose_name='نام محصول'),
        ),
    ]
