"""Data of the demo catalog: products released in 2023 or later (the file name starts with an
underscore so that Django does not treat it as a management command).

Model names and specifications follow the manufacturers' public information.  Prices, stock,
discounts, ratings and delivery times are made-up sample data.  Details that could not be
confirmed with confidence (RAM of the iPhones, battery capacities, weights, ...) are left out.
"""

from dataclasses import dataclass

APPLE_IPHONE = "https://www.apple.com/iphone/compare/"
APPLE_IPAD = "https://www.apple.com/ipad/compare/"
APPLE_AIRPODS = "https://www.apple.com/airpods/"
SAMSUNG_S24_ULTRA = "https://www.samsung.com/global/galaxy/galaxy-s24-ultra/"
SAMSUNG_S25_ULTRA = "https://www.samsung.com/global/galaxy/galaxy-s25-ultra/"

MOBILE, TABLET, AUDIO = "mobile", "tablet", "audio"
APPLE, SAMSUNG = "Apple", "Samsung"


@dataclass(frozen=True)
class Model:
    """One product line with everything that does not depend on storage or color."""

    key: str  # slug prefix
    art: str  # prefix of the picture file names
    brand: str
    category: str
    title: str
    year: int
    os: str  # system software at launch
    chip: str
    network: str  # shown after the chip in the "technology" field
    camera: int  # megapixels of the main rear camera, 0 when there is none
    capability: str
    mini: str
    desc: str
    specs: tuple
    source: str
    storages: tuple = ()  # available storage sizes in GB, empty for products without storage
    has_colors: bool = True  # False when there is one color and one picture (the white AirPods)


MODELS = {
    model.key: model
    for model in [
        # ------------------------------------------------------------ iPhone 2023
        Model(
            key="apple-iphone-15",
            art="iphone-15",
            brand=APPLE,
            category=MOBILE,
            title="iPhone 15",
            year=2023,
            os="iOS 17",
            chip="A16 Bionic",
            network="5G",
            camera=48,
            capability="Dynamic Island",
            mini="A16 Bionic، دوربین ۴۸ مگاپیکسل و درگاه USB-C",
            desc="آیفون ۱۵ در سال ۲۰۲۳ با Dynamic Island، دوربین اصلی ۴۸ مگاپیکسلی و درگاه USB-C عرضه شد؛ تراشهٔ A16 Bionic و نمایشگر OLED آن برای استفادهٔ روزمره و عکاسی مناسب است.",
            specs=(
                "نمایشگر: ۶٫۱ اینچ Super Retina XDR OLED",
                "تراشه: A16 Bionic",
                "دوربین پشت: اصلی ۴۸ مگاپیکسل و اولتراواید ۱۲ مگاپیکسل",
                "ویژگی: Dynamic Island",
                "درگاه: USB-C",
                "شبکه: 5G",
                "سیستم‌عامل هنگام عرضه: iOS 17",
            ),
            source=APPLE_IPHONE,
            storages=(128, 256, 512),
        ),
        Model(
            key="apple-iphone-15-plus",
            art="iphone-15-plus",
            brand=APPLE,
            category=MOBILE,
            title="iPhone 15 Plus",
            year=2023,
            os="iOS 17",
            chip="A16 Bionic",
            network="5G",
            camera=48,
            capability="Dynamic Island",
            mini="نسخهٔ ۶٫۷ اینچی آیفون ۱۵ با دوربین ۴۸ مگاپیکسل",
            desc="آیفون ۱۵ پلاس همان تراشه و دوربین آیفون ۱۵ را با نمایشگر بزرگ‌تر ۶٫۷ اینچی ارائه می‌کند.",
            specs=(
                "نمایشگر: ۶٫۷ اینچ Super Retina XDR OLED",
                "تراشه: A16 Bionic",
                "دوربین پشت: اصلی ۴۸ مگاپیکسل و اولتراواید ۱۲ مگاپیکسل",
                "ویژگی: Dynamic Island",
                "درگاه: USB-C",
                "شبکه: 5G",
                "سیستم‌عامل هنگام عرضه: iOS 17",
            ),
            source=APPLE_IPHONE,
            storages=(128, 256, 512),
        ),
        Model(
            key="apple-iphone-15-pro",
            art="iphone-15-pro",
            brand=APPLE,
            category=MOBILE,
            title="iPhone 15 Pro",
            year=2023,
            os="iOS 17",
            chip="A17 Pro",
            network="5G",
            camera=48,
            capability="ProMotion / Action",
            mini="قاب تیتانیوم، A17 Pro و دکمهٔ Action",
            desc="آیفون ۱۵ پرو نخستین آیفون با قاب تیتانیوم و تراشهٔ A17 Pro است. نمایشگر ProMotion تا ۱۲۰ هرتز، دکمهٔ Action و دوربین سه‌گانه با تله‌فوتو ۳ برابر از ویژگی‌های آن است.",
            specs=(
                "نمایشگر: ۶٫۱ اینچ Super Retina XDR OLED با ProMotion تا ۱۲۰ هرتز",
                "تراشه: A17 Pro",
                "دوربین پشت: اصلی ۴۸ مگاپیکسل، اولتراواید ۱۲ مگاپیکسل و تله‌فوتو ۱۲ مگاپیکسل (۳ برابر اپتیکال)",
                "بدنه: قاب تیتانیوم",
                "ویژگی: دکمهٔ Action",
                "درگاه: USB-C",
                "شبکه: 5G",
                "سیستم‌عامل هنگام عرضه: iOS 17",
            ),
            source=APPLE_IPHONE,
            storages=(128, 256, 512, 1024),
        ),
        Model(
            key="apple-iphone-15-pro-max",
            art="iphone-15-pro-max",
            brand=APPLE,
            category=MOBILE,
            title="iPhone 15 Pro Max",
            year=2023,
            os="iOS 17",
            chip="A17 Pro",
            network="5G",
            camera=48,
            capability="ProMotion / Action",
            mini="تله‌فوتو ۵ برابر، تیتانیوم و نمایشگر ۶٫۷ اینچ",
            desc="آیفون ۱۵ پرو مکس نسخهٔ بزرگ‌تر خانوادهٔ پرو است و برخلاف پرو، تله‌فوتو ۱۲ مگاپیکسلی با بزرگ‌نمایی اپتیکال ۵ برابر دارد.",
            specs=(
                "نمایشگر: ۶٫۷ اینچ Super Retina XDR OLED با ProMotion تا ۱۲۰ هرتز",
                "تراشه: A17 Pro",
                "دوربین پشت: اصلی ۴۸ مگاپیکسل، اولتراواید ۱۲ مگاپیکسل و تله‌فوتو ۱۲ مگاپیکسل (۵ برابر اپتیکال)",
                "بدنه: قاب تیتانیوم",
                "ویژگی: دکمهٔ Action",
                "درگاه: USB-C",
                "شبکه: 5G",
                "سیستم‌عامل هنگام عرضه: iOS 17",
            ),
            source=APPLE_IPHONE,
            storages=(256, 512, 1024),
        ),
        # ------------------------------------------------------------ iPhone 2024
        Model(
            key="apple-iphone-16",
            art="iphone-16",
            brand=APPLE,
            category=MOBILE,
            title="iPhone 16",
            year=2024,
            os="iOS 18",
            chip="A18",
            network="5G",
            camera=48,
            capability="Camera Control",
            mini="A18، دکمهٔ Camera Control و دوربین ۴۸ مگاپیکسل",
            desc="آیفون ۱۶ با تراشهٔ A18، دکمهٔ Camera Control برای کنترل دوربین و دوربین اصلی ۴۸ مگاپیکسلی عرضه شد و iOS 18 را همراه دارد.",
            specs=(
                "نمایشگر: ۶٫۱ اینچ Super Retina XDR OLED",
                "تراشه: A18",
                "دوربین پشت: اصلی Fusion ۴۸ مگاپیکسل و اولتراواید ۱۲ مگاپیکسل",
                "ویژگی: Camera Control و دکمهٔ Action",
                "درگاه: USB-C",
                "شبکه: 5G",
                "سیستم‌عامل هنگام عرضه: iOS 18",
            ),
            source=APPLE_IPHONE,
            storages=(128, 256, 512),
        ),
        Model(
            key="apple-iphone-16-plus",
            art="iphone-16-plus",
            brand=APPLE,
            category=MOBILE,
            title="iPhone 16 Plus",
            year=2024,
            os="iOS 18",
            chip="A18",
            network="5G",
            camera=48,
            capability="Camera Control",
            mini="نسخهٔ ۶٫۷ اینچی آیفون ۱۶ با تراشهٔ A18",
            desc="آیفون ۱۶ پلاس همان تراشه و دوربین آیفون ۱۶ را با نمایشگر بزرگ‌تر ۶٫۷ اینچی ارائه می‌کند.",
            specs=(
                "نمایشگر: ۶٫۷ اینچ Super Retina XDR OLED",
                "تراشه: A18",
                "دوربین پشت: اصلی Fusion ۴۸ مگاپیکسل و اولتراواید ۱۲ مگاپیکسل",
                "ویژگی: Camera Control و دکمهٔ Action",
                "درگاه: USB-C",
                "شبکه: 5G",
                "سیستم‌عامل هنگام عرضه: iOS 18",
            ),
            source=APPLE_IPHONE,
            storages=(128, 256, 512),
        ),
        Model(
            key="apple-iphone-16-pro",
            art="iphone-16-pro",
            brand=APPLE,
            category=MOBILE,
            title="iPhone 16 Pro",
            year=2024,
            os="iOS 18",
            chip="A18 Pro",
            network="5G",
            camera=48,
            capability="Camera Control",
            mini="A18 Pro، تیتانیوم و تله‌فوتو ۵ برابر",
            desc="آیفون ۱۶ پرو با نمایشگر ۶٫۳ اینچی، تراشهٔ A18 Pro، دوربین اولتراواید ۴۸ مگاپیکسلی و تله‌فوتو ۵ برابر عرضه شد.",
            specs=(
                "نمایشگر: ۶٫۳ اینچ Super Retina XDR OLED با ProMotion تا ۱۲۰ هرتز",
                "تراشه: A18 Pro",
                "دوربین پشت: اصلی ۴۸ مگاپیکسل، اولتراواید ۴۸ مگاپیکسل و تله‌فوتو ۱۲ مگاپیکسل (۵ برابر اپتیکال)",
                "بدنه: قاب تیتانیوم",
                "ویژگی: Camera Control و دکمهٔ Action",
                "درگاه: USB-C",
                "شبکه: 5G",
                "سیستم‌عامل هنگام عرضه: iOS 18",
            ),
            source=APPLE_IPHONE,
            storages=(128, 256, 512, 1024),
        ),
        Model(
            key="apple-iphone-16-pro-max",
            art="iphone-16-pro-max",
            brand=APPLE,
            category=MOBILE,
            title="iPhone 16 Pro Max",
            year=2024,
            os="iOS 18",
            chip="A18 Pro",
            network="5G",
            camera=48,
            capability="Camera Control",
            mini="نمایشگر ۶٫۹ اینچی، A18 Pro و تله‌فوتو ۵ برابر",
            desc="آیفون ۱۶ پرو مکس بزرگ‌ترین نمایشگر خانوادهٔ ۱۶ را با تراشهٔ A18 Pro، دوربین اولتراواید ۴۸ مگاپیکسلی و تله‌فوتو ۵ برابر ارائه می‌کند.",
            specs=(
                "نمایشگر: ۶٫۹ اینچ Super Retina XDR OLED با ProMotion تا ۱۲۰ هرتز",
                "تراشه: A18 Pro",
                "دوربین پشت: اصلی ۴۸ مگاپیکسل، اولتراواید ۴۸ مگاپیکسل و تله‌فوتو ۱۲ مگاپیکسل (۵ برابر اپتیکال)",
                "بدنه: قاب تیتانیوم",
                "ویژگی: Camera Control و دکمهٔ Action",
                "درگاه: USB-C",
                "شبکه: 5G",
                "سیستم‌عامل هنگام عرضه: iOS 18",
            ),
            source=APPLE_IPHONE,
            storages=(256, 512, 1024),
        ),
        # ------------------------------------------------------------ iPhone 2025
        Model(
            key="apple-iphone-16e",
            art="iphone-16e",
            brand=APPLE,
            category=MOBILE,
            title="iPhone 16e",
            year=2025,
            os="iOS 18",
            chip="A18",
            network="5G",
            camera=48,
            capability="Action / مودم C1",
            mini="A18، یک دوربین ۴۸ مگاپیکسلی و مودم C1",
            desc="آیفون ۱۶e مدل ساده‌تر خانوادهٔ ۱۶ است با تراشهٔ A18، نمایشگر OLED ۶٫۱ اینچی، یک دوربین پشتی ۴۸ مگاپیکسلی، دکمهٔ Action و مودم C1 ساخت اپل.",
            specs=(
                "نمایشگر: ۶٫۱ اینچ Super Retina XDR OLED",
                "تراشه: A18",
                "دوربین پشت: یک دوربین ۴۸ مگاپیکسلی (Fusion)",
                "ویژگی: دکمهٔ Action و مودم Apple C1",
                "درگاه: USB-C",
                "شبکه: 5G",
                "سیستم‌عامل هنگام عرضه: iOS 18",
            ),
            source=APPLE_IPHONE,
            storages=(128, 256, 512),
        ),
        Model(
            key="apple-iphone-17",
            art="iphone-17",
            brand=APPLE,
            category=MOBILE,
            title="iPhone 17",
            year=2025,
            os="iOS 26",
            chip="A19",
            network="5G",
            camera=48,
            capability="ProMotion ۱۲۰ هرتز",
            mini="A19، نمایشگر ۱۲۰ هرتز و دو دوربین ۴۸ مگاپیکسل",
            desc="آیفون ۱۷ در ۲۰۲۵ با تراشهٔ A19، نمایشگر ۶٫۳ اینچی ProMotion، دو دوربین پشتی ۴۸ مگاپیکسلی و دوربین سلفی ۱۸ مگاپیکسلی Center Stage عرضه شد و iOS 26 را همراه دارد.",
            specs=(
                "نمایشگر: ۶٫۳ اینچ Super Retina XDR OLED با ProMotion تا ۱۲۰ هرتز",
                "تراشه: A19",
                "دوربین پشت: اصلی ۴۸ مگاپیکسل و اولتراواید ۴۸ مگاپیکسل",
                "دوربین سلفی: ۱۸ مگاپیکسل Center Stage",
                "درگاه: USB-C",
                "شبکه: 5G",
                "سیستم‌عامل هنگام عرضه: iOS 26",
            ),
            source=APPLE_IPHONE,
            storages=(256, 512),
        ),
        Model(
            key="apple-iphone-air",
            art="iphone-air",
            brand=APPLE,
            category=MOBILE,
            title="iPhone Air",
            year=2025,
            os="iOS 26",
            chip="A19 Pro",
            network="5G",
            camera=48,
            capability="ضخامت ۵٫۶ میلی‌متر",
            mini="ضخامت ۵٫۶ میلی‌متر، A19 Pro و قاب تیتانیوم",
            desc="آیفون ایر باریک‌ترین آیفون است؛ با ضخامت ۵٫۶ میلی‌متر، قاب تیتانیوم، نمایشگر ۶٫۵ اینچی ProMotion، تراشهٔ A19 Pro و یک دوربین اصلی ۴۸ مگاپیکسلی.",
            specs=(
                "نمایشگر: ۶٫۵ اینچ Super Retina XDR OLED با ProMotion تا ۱۲۰ هرتز",
                "تراشه: A19 Pro",
                "دوربین پشت: یک دوربین اصلی ۴۸ مگاپیکسلی (Fusion)",
                "دوربین سلفی: ۱۸ مگاپیکسل Center Stage",
                "ضخامت: ۵٫۶ میلی‌متر",
                "بدنه: قاب تیتانیوم",
                "درگاه: USB-C",
                "شبکه: 5G",
                "سیستم‌عامل هنگام عرضه: iOS 26",
            ),
            source=APPLE_IPHONE,
            storages=(256, 512, 1024),
        ),
        Model(
            key="apple-iphone-17-pro",
            art="iphone-17-pro",
            brand=APPLE,
            category=MOBILE,
            title="iPhone 17 Pro",
            year=2025,
            os="iOS 26",
            chip="A19 Pro",
            network="5G",
            camera=48,
            capability="Vapor chamber",
            mini="A19 Pro، سه دوربین ۴۸ مگاپیکسل و خنک‌کنندهٔ بخار",
            desc="آیفون ۱۷ پرو با بدنهٔ یکپارچهٔ آلومینیومی، تراشهٔ A19 Pro، سیستم خنک‌کنندهٔ vapor chamber و سه دوربین پشتی ۴۸ مگاپیکسلی عرضه شد.",
            specs=(
                "نمایشگر: ۶٫۳ اینچ Super Retina XDR OLED با ProMotion تا ۱۲۰ هرتز",
                "تراشه: A19 Pro",
                "دوربین پشت: سه دوربین ۴۸ مگاپیکسلی (اصلی، اولتراواید و تله‌فوتو)",
                "دوربین سلفی: ۱۸ مگاپیکسل Center Stage",
                "بدنه: آلومینیوم یکپارچه با خنک‌کنندهٔ vapor chamber",
                "درگاه: USB-C",
                "شبکه: 5G",
                "سیستم‌عامل هنگام عرضه: iOS 26",
            ),
            source=APPLE_IPHONE,
            storages=(256, 512, 1024),
        ),
        Model(
            key="apple-iphone-17-pro-max",
            art="iphone-17-pro-max",
            brand=APPLE,
            category=MOBILE,
            title="iPhone 17 Pro Max",
            year=2025,
            os="iOS 26",
            chip="A19 Pro",
            network="5G",
            camera=48,
            capability="Vapor chamber",
            mini="نمایشگر ۶٫۹ اینچی، A19 Pro و سه دوربین ۴۸ مگاپیکسل",
            desc="آیفون ۱۷ پرو مکس بزرگ‌ترین نمایشگر خانوادهٔ ۱۷ را با تراشهٔ A19 Pro، بدنهٔ یکپارچهٔ آلومینیومی و سه دوربین پشتی ۴۸ مگاپیکسلی ارائه می‌کند.",
            specs=(
                "نمایشگر: ۶٫۹ اینچ Super Retina XDR OLED با ProMotion تا ۱۲۰ هرتز",
                "تراشه: A19 Pro",
                "دوربین پشت: سه دوربین ۴۸ مگاپیکسلی (اصلی، اولتراواید و تله‌فوتو)",
                "دوربین سلفی: ۱۸ مگاپیکسل Center Stage",
                "بدنه: آلومینیوم یکپارچه با خنک‌کنندهٔ vapor chamber",
                "درگاه: USB-C",
                "شبکه: 5G",
                "سیستم‌عامل هنگام عرضه: iOS 26",
            ),
            source=APPLE_IPHONE,
            storages=(256, 512, 1024),
        ),
        # ------------------------------------------------------------ Samsung
        Model(
            key="samsung-galaxy-s24-ultra",
            art="galaxy-s24-ultra",
            brand=SAMSUNG,
            category=MOBILE,
            title="Galaxy S24 Ultra",
            year=2024,
            os="Android 14 / One UI 6.1",
            chip="Snapdragon 8 Gen 3 for Galaxy",
            network="5G",
            camera=200,
            capability="S Pen / Galaxy AI",
            mini="S Pen، دوربین ۲۰۰ مگاپیکسل و قاب تیتانیوم",
            desc="گلکسی S24 اولترا با نمایشگر تخت ۶٫۸ اینچی، قاب تیتانیوم، دوربین اصلی ۲۰۰ مگاپیکسلی، S Pen داخلی و قابلیت‌های Galaxy AI در ۲۰۲۴ عرضه شد.",
            specs=(
                "نمایشگر: ۶٫۸ اینچ Dynamic LTPO AMOLED 2X با نرخ نوسازی ۱ تا ۱۲۰ هرتز",
                "تراشه: Snapdragon 8 Gen 3 for Galaxy",
                "رم: ۱۲ گیگابایت",
                "دوربین پشت: اصلی ۲۰۰ مگاپیکسل، اولتراواید ۱۲ مگاپیکسل، تله‌فوتو ۱۰ مگاپیکسل (۳ برابر) و تله‌فوتو ۵۰ مگاپیکسل (۵ برابر)",
                "دوربین سلفی: ۱۲ مگاپیکسل",
                "باتری: ۵۰۰۰ میلی‌آمپرساعت با شارژ سریع ۴۵ وات",
                "قلم: S Pen داخلی",
                "بدنه: قاب تیتانیوم",
                "شبکه: 5G",
                "سیستم‌عامل هنگام عرضه: Android 14 / One UI 6.1",
            ),
            source=SAMSUNG_S24_ULTRA,
            storages=(256, 512, 1024),
        ),
        Model(
            key="samsung-galaxy-s25-ultra",
            art="galaxy-s25-ultra",
            brand=SAMSUNG,
            category=MOBILE,
            title="Galaxy S25 Ultra",
            year=2025,
            os="Android 15 / One UI 7",
            chip="Snapdragon 8 Elite for Galaxy",
            network="5G",
            camera=200,
            capability="S Pen / Galaxy AI",
            mini="Snapdragon 8 Elite، نمایشگر ۶٫۹ اینچ و S Pen",
            desc="گلکسی S25 اولترا با نمایشگر ۶٫۹ اینچی، تراشهٔ Snapdragon 8 Elite for Galaxy، دوربین اصلی ۲۰۰ مگاپیکسلی، S Pen داخلی و One UI 7 در ۲۰۲۵ عرضه شد.",
            specs=(
                "نمایشگر: ۶٫۹ اینچ Dynamic LTPO AMOLED 2X با نرخ نوسازی ۱ تا ۱۲۰ هرتز",
                "تراشه: Snapdragon 8 Elite for Galaxy",
                "رم: ۱۲ گیگابایت",
                "دوربین پشت: اصلی ۲۰۰ مگاپیکسل، اولتراواید ۵۰ مگاپیکسل، تله‌فوتو ۱۰ مگاپیکسل (۳ برابر) و تله‌فوتو ۵۰ مگاپیکسل (۵ برابر)",
                "دوربین سلفی: ۱۲ مگاپیکسل",
                "باتری: ۵۰۰۰ میلی‌آمپرساعت با شارژ سریع ۴۵ وات",
                "قلم: S Pen داخلی",
                "بدنه: قاب تیتانیوم",
                "شبکه: 5G",
                "سیستم‌عامل هنگام عرضه: Android 15 / One UI 7",
            ),
            source=SAMSUNG_S25_ULTRA,
            storages=(256, 512, 1024),
        ),
        # ------------------------------------------------------------ iPad
        Model(
            key="apple-ipad-pro-13-m4",
            art="ipad-pro-13",
            brand=APPLE,
            category=TABLET,
            title="iPad Pro 13 اینچ M4",
            year=2024,
            os="iPadOS 17",
            chip="Apple M4",
            network="Wi-Fi 6E",
            camera=12,
            capability="Apple Pencil Pro",
            mini="M4، OLED دولایه و ضخامت ۵٫۱ میلی‌متر",
            desc="آیپد پرو ۱۳ اینچی با تراشهٔ M4 و نمایشگر Ultra Retina XDR از نوع OLED دولایه در ۲۰۲۴ عرضه شد؛ ضخامت آن ۵٫۱ میلی‌متر است و از Apple Pencil Pro و Magic Keyboard پشتیبانی می‌کند.",
            specs=(
                "نمایشگر: ۱۳ اینچ Ultra Retina XDR (OLED دولایه)",
                "تراشه: Apple M4",
                "ضخامت: ۵٫۱ میلی‌متر",
                "دوربین پشت: ۱۲ مگاپیکسل",
                "دوربین جلو: ۱۲ مگاپیکسل اولتراواید",
                "احراز هویت: Face ID",
                "درگاه: USB-C با Thunderbolt / USB 4",
                "مدل: Wi-Fi",
                "پشتیبانی: Apple Pencil Pro و Magic Keyboard",
                "سیستم‌عامل هنگام عرضه: iPadOS 17",
            ),
            source=APPLE_IPAD,
            storages=(256, 512, 1024, 2048),
        ),
        Model(
            key="apple-ipad-pro-11-m4",
            art="ipad-pro-11",
            brand=APPLE,
            category=TABLET,
            title="iPad Pro 11 اینچ M4",
            year=2024,
            os="iPadOS 17",
            chip="Apple M4",
            network="Wi-Fi 6E",
            camera=12,
            capability="Apple Pencil Pro",
            mini="M4، OLED دولایه و ضخامت ۵٫۳ میلی‌متر",
            desc="آیپد پرو ۱۱ اینچی با تراشهٔ M4 و نمایشگر Ultra Retina XDR از نوع OLED دولایه در ۲۰۲۴ عرضه شد؛ ضخامت آن ۵٫۳ میلی‌متر است و از Apple Pencil Pro و Magic Keyboard پشتیبانی می‌کند.",
            specs=(
                "نمایشگر: ۱۱ اینچ Ultra Retina XDR (OLED دولایه)",
                "تراشه: Apple M4",
                "ضخامت: ۵٫۳ میلی‌متر",
                "دوربین پشت: ۱۲ مگاپیکسل",
                "دوربین جلو: ۱۲ مگاپیکسل اولتراواید",
                "احراز هویت: Face ID",
                "درگاه: USB-C با Thunderbolt / USB 4",
                "مدل: Wi-Fi",
                "پشتیبانی: Apple Pencil Pro و Magic Keyboard",
                "سیستم‌عامل هنگام عرضه: iPadOS 17",
            ),
            source=APPLE_IPAD,
            storages=(256, 512, 1024, 2048),
        ),
        Model(
            key="apple-ipad-pro-13-m5",
            art="ipad-pro-13",
            brand=APPLE,
            category=TABLET,
            title="iPad Pro 13 اینچ M5",
            year=2025,
            os="iPadOS 26",
            chip="Apple M5",
            network="Wi-Fi 7",
            camera=12,
            capability="Apple Pencil Pro",
            mini="M5، OLED دولایه و Wi-Fi 7",
            desc="آیپد پرو ۱۳ اینچی با تراشهٔ M5 در ۲۰۲۵ عرضه شد؛ نمایشگر OLED دولایه، تراشهٔ بی‌سیم Apple N1 با Wi-Fi 7 و iPadOS 26 از ویژگی‌های آن است.",
            specs=(
                "نمایشگر: ۱۳ اینچ Ultra Retina XDR (OLED دولایه)",
                "تراشه: Apple M5",
                "تراشهٔ بی‌سیم: Apple N1 (Wi-Fi 7)",
                "دوربین پشت: ۱۲ مگاپیکسل",
                "احراز هویت: Face ID",
                "درگاه: USB-C با Thunderbolt / USB 4",
                "مدل: Wi-Fi",
                "پشتیبانی: Apple Pencil Pro و Magic Keyboard",
                "سیستم‌عامل هنگام عرضه: iPadOS 26",
            ),
            source=APPLE_IPAD,
            storages=(256, 512, 1024, 2048),
        ),
        Model(
            key="apple-ipad-pro-11-m5",
            art="ipad-pro-11",
            brand=APPLE,
            category=TABLET,
            title="iPad Pro 11 اینچ M5",
            year=2025,
            os="iPadOS 26",
            chip="Apple M5",
            network="Wi-Fi 7",
            camera=12,
            capability="Apple Pencil Pro",
            mini="M5، OLED دولایه و Wi-Fi 7",
            desc="آیپد پرو ۱۱ اینچی با تراشهٔ M5 در ۲۰۲۵ عرضه شد؛ نمایشگر OLED دولایه، تراشهٔ بی‌سیم Apple N1 با Wi-Fi 7 و iPadOS 26 از ویژگی‌های آن است.",
            specs=(
                "نمایشگر: ۱۱ اینچ Ultra Retina XDR (OLED دولایه)",
                "تراشه: Apple M5",
                "تراشهٔ بی‌سیم: Apple N1 (Wi-Fi 7)",
                "دوربین پشت: ۱۲ مگاپیکسل",
                "احراز هویت: Face ID",
                "درگاه: USB-C با Thunderbolt / USB 4",
                "مدل: Wi-Fi",
                "پشتیبانی: Apple Pencil Pro و Magic Keyboard",
                "سیستم‌عامل هنگام عرضه: iPadOS 26",
            ),
            source=APPLE_IPAD,
            storages=(256, 512, 1024, 2048),
        ),
        Model(
            key="apple-ipad-air-11-m3",
            art="ipad-air-11",
            brand=APPLE,
            category=TABLET,
            title="iPad Air 11 اینچ M3",
            year=2025,
            os="iPadOS 18",
            chip="Apple M3",
            network="Wi-Fi 6E",
            camera=12,
            capability="Apple Pencil Pro",
            mini="M3، نمایشگر Liquid Retina ۱۱ اینچ",
            desc="آیپد ایر ۱۱ اینچی با تراشهٔ M3 در ۲۰۲۵ عرضه شد و از Apple Pencil Pro و Magic Keyboard پشتیبانی می‌کند.",
            specs=(
                "نمایشگر: ۱۱ اینچ Liquid Retina",
                "تراشه: Apple M3",
                "دوربین پشت: ۱۲ مگاپیکسل",
                "دوربین جلو: ۱۲ مگاپیکسل",
                "احراز هویت: Touch ID",
                "درگاه: USB-C",
                "مدل: Wi-Fi",
                "پشتیبانی: Apple Pencil Pro و Magic Keyboard",
                "سیستم‌عامل هنگام عرضه: iPadOS 18",
            ),
            source=APPLE_IPAD,
            storages=(128, 256, 512, 1024),
        ),
        Model(
            key="apple-ipad-mini-a17-pro",
            art="ipad-mini",
            brand=APPLE,
            category=TABLET,
            title="iPad mini A17 Pro",
            year=2024,
            os="iPadOS 18",
            chip="Apple A17 Pro",
            network="Wi-Fi 6E",
            camera=12,
            capability="Apple Pencil Pro",
            mini="A17 Pro، نمایشگر ۸٫۳ اینچی و Apple Pencil Pro",
            desc="آیپد مینی با تراشهٔ A17 Pro در ۲۰۲۴ عرضه شد؛ نمایشگر Liquid Retina ۸٫۳ اینچی، درگاه USB-C و پشتیبانی از Apple Pencil Pro و Apple Intelligence دارد.",
            specs=(
                "نمایشگر: ۸٫۳ اینچ Liquid Retina",
                "تراشه: Apple A17 Pro",
                "دوربین پشت: ۱۲ مگاپیکسل",
                "دوربین جلو: ۱۲ مگاپیکسل",
                "احراز هویت: Touch ID",
                "درگاه: USB-C",
                "مدل: Wi-Fi",
                "پشتیبانی: Apple Pencil Pro و Apple Intelligence",
                "سیستم‌عامل هنگام عرضه: iPadOS 18",
            ),
            source=APPLE_IPAD,
            storages=(128, 256, 512),
        ),
        Model(
            key="apple-ipad-a16",
            art="ipad",
            brand=APPLE,
            category=TABLET,
            title="iPad A16",
            year=2025,
            os="iPadOS 18",
            chip="Apple A16",
            network="Wi-Fi 6",
            camera=12,
            capability="Apple Pencil USB-C",
            mini="A16، نمایشگر Liquid Retina ۱۱ اینچ",
            desc="آیپد با تراشهٔ A16 در ۲۰۲۵ عرضه شد؛ نمایشگر Liquid Retina ۱۱ اینچی، درگاه USB-C و دوربین‌های ۱۲ مگاپیکسلی دارد.",
            specs=(
                "نمایشگر: ۱۱ اینچ Liquid Retina",
                "تراشه: Apple A16",
                "دوربین پشت: ۱۲ مگاپیکسل",
                "دوربین جلو: ۱۲ مگاپیکسل",
                "احراز هویت: Touch ID",
                "درگاه: USB-C",
                "مدل: Wi-Fi",
                "پشتیبانی: Apple Pencil (USB-C)",
                "سیستم‌عامل هنگام عرضه: iPadOS 18",
            ),
            source=APPLE_IPAD,
            storages=(128, 256, 512),
        ),
        # ------------------------------------------------------------ AirPods
        Model(
            key="apple-airpods-pro-3",
            art="airpods-pro-3",
            brand=APPLE,
            category=AUDIO,
            title="AirPods Pro 3",
            year=2025,
            os="iOS 26 / iPadOS 26",
            chip="H2",
            network="Bluetooth",
            camera=0,
            capability="حذف نویز فعال",
            mini="H2، حذف نویز فعال و حسگر ضربان قلب",
            desc="ایرپاد پرو ۳ با تراشهٔ H2، حذف نویز فعال، مقاومت IP57، حسگر ضربان قلب و نوک‌های سیلیکونی فوم‌دار در پنج اندازه در ۲۰۲۵ عرضه شد.",
            specs=(
                "تراشه: Apple H2",
                "ویژگی: حذف نویز فعال",
                "حسگر: ضربان قلب",
                "مقاومت: IP57",
                "نوک گوشی: سیلیکونی با فوم، در پنج اندازه",
                "کیس شارژ: USB-C",
                "سیستم‌عامل هنگام عرضه: iOS 26 / iPadOS 26",
            ),
            source=APPLE_AIRPODS,
            has_colors=False,
        ),
        Model(
            key="apple-airpods-pro-2-usb-c",
            art="airpods-pro-2",
            brand=APPLE,
            category=AUDIO,
            title="AirPods Pro 2 USB-C",
            year=2023,
            os="iOS 17 / iPadOS 17",
            chip="H2",
            network="Bluetooth",
            camera=0,
            capability="حذف نویز فعال",
            mini="H2، حذف نویز فعال و کیس USB-C",
            desc="ایرپاد پرو ۲ با کیس شارژ USB-C در ۲۰۲۳ عرضه شد؛ تراشهٔ H2، حذف نویز فعال، حالت Adaptive Audio و مقاومت IP54 دارد.",
            specs=(
                "تراشه: Apple H2",
                "ویژگی: حذف نویز فعال، حالت Transparency و Adaptive Audio",
                "مقاومت: IP54 برای گوشی‌ها و کیس",
                "کیس شارژ: USB-C، قابل شارژ با MagSafe، Apple Watch یا Qi",
                "باتری: تا ۶ ساعت شنیدن با یک بار شارژ و تا ۳۰ ساعت با کیس",
                "کنترل: لمسی روی ساقه",
                "سیستم‌عامل هنگام عرضه: iOS 17 / iPadOS 17",
            ),
            source=APPLE_AIRPODS,
            has_colors=False,
        ),
        Model(
            key="apple-airpods-4",
            art="airpods-4",
            brand=APPLE,
            category=AUDIO,
            title="AirPods 4",
            year=2024,
            os="iOS 18 / iPadOS 18",
            chip="H2",
            network="Bluetooth",
            camera=0,
            capability="Spatial Audio",
            mini="H2، طراحی جدید و کیس USB-C",
            desc="ایرپاد ۴ با طراحی جدید و بدون نوک سیلیکونی و تراشهٔ H2 در ۲۰۲۴ عرضه شد؛ کیس آن USB-C است و گوشی‌ها مقاومت IP54 دارند.",
            specs=(
                "تراشه: Apple H2",
                "طراحی: بدون نوک سیلیکونی",
                "ویژگی: Personalized Spatial Audio",
                "مقاومت: IP54",
                "کیس شارژ: USB-C",
                "سیستم‌عامل هنگام عرضه: iOS 18 / iPadOS 18",
            ),
            source=APPLE_AIRPODS,
            has_colors=False,
        ),
        Model(
            key="apple-airpods-4-anc",
            art="airpods-4-anc",
            brand=APPLE,
            category=AUDIO,
            title="AirPods 4 با حذف نویز",
            year=2024,
            os="iOS 18 / iPadOS 18",
            chip="H2",
            network="Bluetooth",
            camera=0,
            capability="حذف نویز فعال",
            mini="حذف نویز فعال، H2 و کیس شارژ بی‌سیم",
            desc="نسخهٔ ایرپاد ۴ با حذف نویز فعال، حالت Adaptive Audio و Transparency و کیس USB-C با شارژ بی‌سیم در ۲۰۲۴ عرضه شد.",
            specs=(
                "تراشه: Apple H2",
                "طراحی: بدون نوک سیلیکونی",
                "ویژگی: حذف نویز فعال، Adaptive Audio و حالت Transparency",
                "مقاومت: IP54",
                "کیس شارژ: USB-C با شارژ بی‌سیم",
                "سیستم‌عامل هنگام عرضه: iOS 18 / iPadOS 18",
            ),
            source=APPLE_AIRPODS,
            has_colors=False,
        ),
        Model(
            key="apple-airpods-max-usb-c",
            art="airpods-max",
            brand=APPLE,
            category=AUDIO,
            title="AirPods Max USB-C",
            year=2024,
            os="iOS 18 / iPadOS 18",
            chip="H1",
            network="Bluetooth",
            camera=0,
            capability="حذف نویز فعال",
            mini="H1، حذف نویز فعال و درگاه USB-C",
            desc="ایرپاد مکس با درگاه USB-C در ۲۰۲۴ عرضه شد؛ هدفون روگوشی با حذف نویز فعال، Adaptive EQ، Spatial Audio و باتری تا ۲۰ ساعت (با حذف نویز).",
            specs=(
                "تراشه: Apple H1 در هر گوشی",
                "ویژگی: حذف نویز فعال و حالت Transparency",
                "صدا: Adaptive EQ و Spatial Audio با ردیابی حرکت سر",
                "درگاه: USB-C",
                "باتری: تا ۲۰ ساعت با حذف نویز فعال",
                "کنترل: Digital Crown",
                "سیستم‌عامل هنگام عرضه: iOS 18 / iPadOS 18",
            ),
            source=APPLE_AIRPODS,
        ),
    ]
}

# Persian names of the colors.  They describe the look of the picture; they are not the
# manufacturers' marketing names.
COLORS = {
    "white": "سفید",
    "black": "مشکی",
    "space-black": "مشکی",
    "midnight": "مشکی",
    "silver": "نقره‌ای",
    "cosmic-orange": "نارنجی",
    "orange": "نارنجی",
    "deep-blue": "آبی سرمه‌ای",
    "sky-blue": "آبی آسمانی",
    "mist-blue": "آبی روشن",
    "blue": "آبی",
    "ultramarine": "آبی کبالتی",
    "light-gold": "طلایی",
    "lavender": "یاسی",
    "purple": "بنفش",
    "pink": "صورتی",
    "teal": "سبزآبی",
    "green": "سبز",
    "yellow": "زرد",
    "starlight": "کرم",
    "natural-titanium": "تیتانیوم طبیعی",
    "white-titanium": "تیتانیوم سفید",
    "black-titanium": "تیتانیوم مشکی",
    "blue-titanium": "تیتانیوم آبی",
    "desert-titanium": "تیتانیوم شنی",
    "titanium-gray": "تیتانیوم خاکستری",
    "titanium-black": "تیتانیوم مشکی",
    "titanium-silverblue": "آبی نقره‌ای",
}


@dataclass(frozen=True)
class Variant:
    """One sellable product: a model in one storage size and color, with its demo commerce data."""

    model: str
    storage: int | None  # GB, None for products without storage
    color: str
    price: int  # toman
    offer: int  # percent
    stock: int
    rate: str


def _variant(brand_prefix, model, storage, color, price, offer, stock, rate):
    return Variant(f"{brand_prefix}-{model}", storage, color, price, offer, stock, rate)


def _v(model, *details):
    """A variant of an Apple product line (the model name is written without the brand prefix)."""
    return _variant("apple", model, *details)


def _samsung(model, *details):
    return _variant("samsung", model, *details)


MILLION = 1_000_000  # prices are easier to read in millions of toman

# The newest products come first.  Every price grows with the storage size and with the generation.
# Columns: model, storage (GB), color, price (toman), discount (%), stock, rating.
VARIANTS = [
    # 2025
    _v("iphone-17-pro-max", 256, "cosmic-orange", 189 * MILLION, 5, 12, "4.9"),
    _v("iphone-17-pro-max", 512, "deep-blue", 214 * MILLION, 0, 8, "4.9"),
    _v("iphone-17-pro-max", 1024, "silver", 249 * MILLION, 0, 4, "4.8"),
    _v("iphone-17-pro", 256, "silver", 168 * MILLION, 0, 14, "4.9"),
    _v("iphone-17-pro", 512, "deep-blue", 192 * MILLION, 0, 9, "4.8"),
    _v("iphone-air", 256, "sky-blue", 139 * MILLION, 5, 11, "4.8"),
    _v("iphone-air", 512, "space-black", 162 * MILLION, 0, 6, "4.8"),
    _v("iphone-air", 256, "light-gold", 139 * MILLION, 0, 7, "4.7"),
    _v("iphone-17", 256, "lavender", 112 * MILLION, 6, 18, "4.8"),
    _v("iphone-17", 256, "black", 112 * MILLION, 0, 20, "4.8"),
    _v("iphone-17", 512, "mist-blue", 134 * MILLION, 0, 10, "4.7"),
    _v("iphone-16e", 128, "black", 62 * MILLION, 8, 16, "4.6"),
    _v("iphone-16e", 256, "white", 74 * MILLION, 0, 9, "4.5"),
    _samsung("galaxy-s25-ultra", 256, "titanium-silverblue", 118 * MILLION, 6, 10, "4.8"),
    _samsung("galaxy-s25-ultra", 512, "titanium-black", 134 * MILLION, 0, 5, "4.7"),
    _v("ipad-pro-13-m5", 256, "space-black", 138 * MILLION, 0, 6, "4.9"),
    _v("ipad-pro-11-m5", 256, "silver", 108 * MILLION, 0, 8, "4.8"),
    _v("ipad-air-11-m3", 128, "blue", 52 * MILLION, 7, 13, "4.7"),
    _v("ipad-air-11-m3", 256, "purple", 61 * MILLION, 0, 9, "4.6"),
    _v("ipad-a16", 128, "yellow", 29 * MILLION, 10, 19, "4.4"),
    _v("ipad-a16", 256, "pink", 37 * MILLION, 0, 12, "4.3"),
    _v("airpods-pro-3", None, "white", 21_500_000, 0, 15, "4.9"),
    # 2024
    _v("iphone-16-pro-max", 256, "desert-titanium", 142 * MILLION, 10, 7, "4.7"),
    _v("iphone-16-pro", 128, "natural-titanium", 108 * MILLION, 0, 10, "4.7"),
    _v("iphone-16-pro", 256, "white-titanium", 121 * MILLION, 0, 6, "4.6"),
    _v("iphone-16-plus", 128, "ultramarine", 84 * MILLION, 0, 11, "4.5"),
    _v("iphone-16", 128, "pink", 73 * MILLION, 12, 15, "4.6"),
    _v("iphone-16", 256, "teal", 86 * MILLION, 0, 9, "4.5"),
    _samsung("galaxy-s24-ultra", 256, "titanium-gray", 92 * MILLION, 14, 5, "4.5"),
    _v("ipad-pro-13-m4", 256, "silver", 118 * MILLION, 9, 5, "4.7"),
    _v("ipad-pro-11-m4", 256, "space-black", 92 * MILLION, 0, 6, "4.6"),
    _v("ipad-mini-a17-pro", 128, "starlight", 41 * MILLION, 0, 10, "4.6"),
    _v("ipad-mini-a17-pro", 256, "blue", 49 * MILLION, 0, 7, "4.5"),
    _v("airpods-4", None, "white", 11_900_000, 10, 20, "4.5"),
    _v("airpods-4-anc", None, "white", 14_900_000, 0, 14, "4.6"),
    _v("airpods-max-usb-c", None, "midnight", 36 * MILLION, 8, 6, "4.5"),
    _v("airpods-max-usb-c", None, "orange", 36 * MILLION, 0, 4, "4.4"),
    # 2023
    _v("iphone-15-pro-max", 256, "natural-titanium", 112 * MILLION, 12, 6, "4.6"),
    _v("iphone-15-pro-max", 512, "blue-titanium", 131 * MILLION, 0, 4, "4.5"),
    _v("iphone-15-pro", 128, "black-titanium", 88 * MILLION, 0, 7, "4.5"),
    _v("iphone-15-plus", 128, "green", 68 * MILLION, 0, 8, "4.3"),
    _v("iphone-15", 128, "blue", 58 * MILLION, 15, 14, "4.4"),
    _v("airpods-pro-2-usb-c", None, "white", 16_800_000, 12, 18, "4.6"),
]
