# Generated by Django 4.2.6 on 2024-03-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_category_category_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_rate",
            field=models.DecimalField(
                decimal_places=1, max_digits=3, verbose_name="امتیاز"
            ),
        ),
    ]
