# Generated by Django 5.0.4 on 2026-10-07 22:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_alter_product_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="discounted_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="تخفیف محصول",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="offer",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="درصد تخفیف",
            ),
        ),
    ]
